export GLOBAL_PYTHON_VERSION=3.12.13
export GLOBAL_NODE_VERSION=24.18.0
GLOBAL_PYTHON_PATH="$HOME/.pyenv/versions/$GLOBAL_PYTHON_VERSION/bin/python"
[ -x "$GLOBAL_PYTHON_PATH" ] || GLOBAL_PYTHON_PATH=
export GLOBAL_PYTHON_PATH
GLOBAL_NODE_PATH="$HOME/.nvm/versions/node/v$GLOBAL_NODE_VERSION/bin/node"
[ -x "$GLOBAL_NODE_PATH" ] || GLOBAL_NODE_PATH=
export GLOBAL_NODE_PATH

export WORKSPACE="${WORKSPACE:-}"
