sub-auto=all
sub-visibility=yes
sub-ass-override=force

sub-font-size=36
sub-font="Helvetica Neue"
sub-color="#FFFFFF"
sub-border-color="#000000"
sub-border-size=2
sub-shadow-offset=1
sub-shadow-color="#000000"

sub-pos=90
# sub-max-lines=4
sub-delay=0

